### ISSUE TITLE
Problems While Compiling on Ubuntu 16

### ISSUE THREAD

**Issue by duduRodrigues** [TUWien/ReadFramework#12]
I've installed all the needed dependencies, but when I run the make command i keep getting this error: 
![screenshot from 2017-09-19 20-26-06](https://user-images.githubusercontent.com/10099698/30619971-006eec7c-9d79-11e7-959a-3031015108ab.png)

What should I do to fix it?

**Comment by diemmarkus** [comment]
hi,
there was a change in the OpenCV interface - which OpenCV version are you using?

**Comment by duduRodrigues** [comment]
I'm using OpenCV 3.3.0

**Comment by diemmarkus** [comment]
compiling with opencv 3.3 is fixed now
